[platformio]
; Set the default environment to your current breadboard setup
default_envs = breadboard

; ---------------------------------------------------
; Shared Settings (Applies to all environments)
; ---------------------------------------------------
[env]
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
check_skip_packages = yes

lib_deps = 
    https://github.com/tzapu/WiFiManager
    thomasfredericks/Bounce2@^2.70
    https://github.com/gfvalvo/NewEncoder
    yergin/YetAnotherButtonLibrary@^0.1.1
    robtillaart/ADS1X15@^0.3.5
    bodmer/TFT_eSPI @ ^2.5.31
    mathworks/ThingSpeak

; Shared Build Flags
build_flags = 
 ; comment out the following line to enable debug output
 ;   -DWM_NODEBUG=1
    -I include

; ---------------------------------------------------
; Environment 1: Breadboard (ESP32 Firebeetle V4)
; ---------------------------------------------------
[env:breadboard]
platform = espressif32
board = firebeetle32
upload_port = /dev/ttyUSB*
monitor_port = /dev/ttyUSB*
monitor_speed = 115200
build_flags =
    ${env.build_flags}
    -D ENV_BREADBOARD
    -D USE_ADS1015
    -D PIN_I2C_SDA=21
    -D PIN_I2C_SCL=22
    -D PIN_ENCODER_A=5
    -D PIN_ENCODER_B=2
    -D PIN_ENCODER_BTN=0
    -D PIN_TFT_MOSI=23
    -D PIN_TFT_SCLK=18
    -D PIN_TFT_CS=10
    -D PIN_TFT_DC=13
    -D PIN_TFT_RST=27
    -D PIN_TFT_BLK=9
    -D USER_SETUP_LOADED=1
    -D GC9A01_DRIVER=1
    -D TFT_MOSI=PIN_TFT_MOSI
    -D TFT_SCLK=PIN_TFT_SCLK
    -D TFT_CS=PIN_TFT_CS
    -D TFT_DC=PIN_TFT_DC
    -D TFT_RST=PIN_TFT_RST
    -D LOAD_GLCD=1
    -D SPI_FREQUENCY=27000000

; ---------------------------------------------------
; Environment 2: cloudSmoker2 PCB (ESP32-C3)
; ---------------------------------------------------
[env:cloudsmoker2]
platform = espressif32
board = esp32-c3-devkitm-1
build_flags =
    ${env.build_flags}
    -D ENV_PCB
    -D USE_ADS1115
    -D ARDUINO_USB_MODE=1 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D PIN_ENCODER_A=1
    -D PIN_ENCODER_B=2
    -D PIN_ENCODER_BTN=3
    -D PIN_I2C_SDA=5
    -D PIN_I2C_SCL=6
    -D PIN_BUZZER=7

; ---------------------------------------------------
; Environment 3: Unit Testing (Native PC)
; ---------------------------------------------------
[env:native]
platform = native