M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-06-14T13:09:34+0930
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-14T13:09:34+09:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X64.595Y54.39
X64.595Y48.61
T2
X37.9Y66.0
X44.825Y66.0
M30
